# Generated by Django 4.2.4 on 2023-08-16 19:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('i_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='I_ID')),
                ('i_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
