# Generated by Django 4.2.4 on 2023-08-16 19:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='C_ID')),
                ('c_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
