# Generated by Django 4.2.4 on 2023-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('e_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='E_ID')),
                ('e_board', models.CharField(max_length=255)),
                ('e_institute', models.CharField(max_length=255)),
                ('e_degree', models.CharField(max_length=255)),
                ('e_marks', models.CharField(max_length=25)),
                ('e_metric', models.CharField(choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage')], max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
    ]
