# Generated by Django 4.2.4 on 2023-08-16 20:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='EXP_ID')),
                ('exp_title', models.CharField(max_length=255)),
                ('exp_company', models.CharField(max_length=255)),
                ('exp_description', tinymce.models.HTMLField()),
                ('from_date', models.DateField()),
                ('exp_current', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
