# Generated by Django 4.2.4 on 2023-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='resume_phone',
            field=models.BigIntegerField(),
        ),
    ]
