# Generated by Django 4.2.4 on 2023-08-12 20:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('w_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='W_ID')),
                ('w_flow', tinymce.models.HTMLField()),
            ],
        ),
    ]
